# Generated by Django 4.1.5 on 2023-02-17 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['pk']},
        ),
    ]
