# Generated by Django 4.1.5 on 2023-03-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_alter_list_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["display_order", "priority", "-date_added"]},
        ),
        migrations.AddField(
            model_name="task",
            name="display_order",
            field=models.IntegerField(default=50000),
        ),
    ]
