# Generated by Django 4.1.5 on 2023-03-10 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_task_options_task_display_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["display_order"]},
        ),
        migrations.RemoveField(
            model_name="task",
            name="priority",
        ),
    ]
