# Generated by Django 4.1.5 on 2023-03-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0008_alter_task_options_remove_task_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="display_order",
            field=models.IntegerField(default=1),
        ),
    ]
