# Generated by Django 4.1.5 on 2023-03-09 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("display_order", models.IntegerField(default=1)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("notes", models.TextField(blank=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("user_date", models.DateTimeField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "First thing"),
                            (2, "ASAP"),
                            (3, "Soon"),
                            (4, "Whenever"),
                        ],
                        default=3,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "lists",
                    models.ManyToManyField(related_name="tasks", to="tasks.list"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-date_added"],
            },
        ),
        migrations.DeleteModel(
            name="ListTasks"),
    ]
